### ISSUE TITLE
Link Error

### ISSUE THREAD

**Issue by Ansujit** [sarandogou/webrtc-everywhere#13]
I am building the webrtc-everywhere 1.2.0 for windows .
Using windows-7 and visual studio 2013.

I am getting link errors while building the project solution.

error LNK1104: cannot open file 'crssl.lib'

Can you suggest any solution for this.

**Comment by sarandogou** [comment]
Fixed in fb712acd23440c55ab3bed4d6fbaa9e221ef8340
