### ISSUE TITLE
where to find crssl.lib after building google's webrtc code

### ISSUE THREAD

**Issue by princearokiadask** [sarandogou/webrtc-everywhere#21]
Hi guys,

As per your answer for another question here 
https://github.com/sarandogou/webrtc-everywhere/issues/13, 
we got the googles webrtc code and build it successfully. But we couldn't find the crssl.lib anywhere in build structure. Can you help with instructions to find those libs ?

**Comment by sarandogou** [comment]
Fixed in fb712acd23440c55ab3bed4d6fbaa9e221ef8340
