### ISSUE TITLE
Not able to use the mac source code

### ISSUE THREAD

**Issue by puneetxc** [sarandogou/webrtc-everywhere#26]
It shows file missing error
![screen shot 2015-05-04 at 12 31 37 pm](https://cloud.githubusercontent.com/assets/7820873/7452467/652218de-f27b-11e4-9db2-d12b5eb76a03.png)

Also a lot of other files are missing too. Could you please let me know how can i make the new dmg file with all the issues resolved. I need the latest dmg file

**Comment by joshuairl** [comment]
Having the same issues, thought about linking the files from thirdparty folder but they aren't there.  refcount.h is under `talk/base/` but it's causing other errors too.

**Comment by joshuairl** [comment]
I'm too new to XCode and Objective-C to really be able to muddle through the proper linking of the directories since they aren't defined in the project.

**Comment by sarandogou** [comment]
This is a known issue. We updated the WebRTC versions but not the headers and binaries for OS X. Should be fixed in the coming days.

**Comment by joshuairl** [comment]
What's the status on this? Any update?
Is there not a webrtc/base/refcount.h located elsewhere that we could go ahead and update?

**Comment by cgupta** [comment]
Any update on this will be great

**Comment by sarandogou** [comment]
Use latest source code and follow https://github.com/sarandogou/webrtc-everywhere#building-source-code

**Comment by sarandogou** [comment]
Closed by release 2.0.0
