### ISSUE TITLE
High memory and cpu utilization while using webtrc -everywhere plugin in IE browser

### ISSUE THREAD

**Issue by ANANDHAKUMARS** [sarandogou/webrtc-everywhere#28]
We were using webtrc everywhere plugin in peer connection for our project. it is working fine upto 2 streams. while it exceeds 2 streams, CPU and memory utilization reaching its maximum point and the IE browser got crashed and system got hanged. Can you please throw in some light to solve this issue?

![screenshot 6](https://cloud.githubusercontent.com/assets/8692201/7806308/e39514aa-039c-11e5-86e4-2f4889682f54.png)

**Comment by sarandogou** [comment]
What about the same scenario with Chrome?
Do you have sample JS code we can use to test?

**Comment by ANANDHAKUMARS** [comment]
No issues with chrome. Its working fine with same number of streams. In case of IE, it getting crashed.


if(getBrowser() === 'ieAndSafari') {
webrtcPlugin();   //Contains adapter.js code
 }

This is how we are finding the browser and loading the plug-in at the window loading.

At a certain step, we are calling 
navigator.getUserMedia(constraints, successCallBack, errorCallBack)

For peer connection, 
peerConnection = new RTCPeerConnection(pc_config, con);

When peer connection starts increasing, CPU usage gets high stably. After reaching 7 streams, CPU usage rises to 100% and system gets crashed.

**Comment by sarandogou** [comment]
https://groups.google.com/forum/#!topic/webrtc-everywhere/i772nOQ1Bnk

**Comment by sarandogou** [comment]
Will be fixed in the next release.

**Comment by sarandogou** [comment]
Closed by release 2.0.0
