### ISSUE TITLE
OSX Download URL Broken

### ISSUE THREAD

**Issue by rosskukulinski** [sarandogou/webrtc-everywhere#35]
The link in README.md to download the plugin for OSX is currently broken (404 error)

https://doubango.org/webrtc/webrtc-everywhere-i386-10.4.dmg

**Comment by sarandogou** [comment]
You should update your code. The right URL: https://doubango.org/webrtc/webrtc-everywhere-10.6.dmg
We removed "i386" from the name as now we use universal binaries (both i386 and x86_64)

**Comment by rosskukulinski** [comment]
@sarandogou that's fine... but you should update README.md as it still links to 10.4:
https://github.com/sarandogou/webrtc-everywhere/blob/master/README.md#downloads
