### ISSUE TITLE
webrtc-everywhere-console.exe not working

### ISSUE THREAD

**Issue by nagarjunabandi** [sarandogou/webrtc-everywhere#47]
I have compiled webrtc and webrtc-everywhere projects in windows and successfully generated the dll's and exe, but when I try to run the console I am getting the below error. Please help me if I miss something. When I download the setup and install it is working fine in IE with the samples provided.
---------------------------------------------------------------------------------------------------------------
*INFO: _MediaStreamTrackAudio::~_MediaStreamTrackAudio
*INFO: _MediaStreamTrack::~_MediaStreamTrack
**ERROR: function: "_MediaStreamTrackVideo::_MediaStreamTrackVideo()"
file: "_MediaStreamTrack.cc"
line: "291"
MSG: Failed to open video capture device
*INFO: _MediaStreamTrackVideo::~_MediaStreamTrackVideo
*INFO: _MediaStreamTrack::~_MediaStreamTrack
*INFO: _RTCPeerConnection::OnRenegotiationNeeded
*INFO: ~DummyCreateSessionDescriptionObserver
*INFO: _MediaStreamTrackAudio::~_MediaStreamTrackAudio
*INFO: _MediaStreamTrack::~_MediaStreamTrack
*INFO: audioTracks.size() = 1
*INFO: videoTracks.size() = 0
*INFO: AudioTrack: 2_audio_track, audio, 5
*INFO: _MediaStreamTrackAudio::~_MediaStreamTrackAudio
*INFO: _MediaStreamTrack::~_MediaStreamTrack
*INFO: _MediaStream::~_MediaStream
------------------------------------------------------------------------------------------------------------------------

**Comment by sarandogou** [comment]
Why do you want to test the console app?
This is the expected result.

**Comment by nagarjunabandi** [comment]
Hi Thanks for your quick reply, can you please let me know why the opening of video capture device failed when I linked the webrtc-everywhere-common.dll of compiled source code that you provided, but the same case is executing successfully without any error when I try to link the webrtc-everywhere-common.dll from the setup you have provided. Is the dll generated from the source code that you have provided?

**Comment by SantoshBhivase** [comment]
Hello,
I am also facing same issue, nagarjunabandi are able to resolve this ?
If yes let me know what is missing.
Thanks
